[package]
name = "test_baz"
version = "0.1.0"
edition = "2021"

[package.metadata.verus]
verify = true

[dependencies]
vstd = { git = "https://github.com/verus-lang/verus", rev = "33c6cec7bd19818e51d2b61f629d5d2484778bed"}

[[bin]]
name = "test_false"
path = "src/test_false.rs"
